const _ = {
  Bolivia: "Bolivia (Plurinational State of)",
  Tanzania: "Tanzania, United Republic of",
  "Solomon Is.": "Solomon Islands",
  "Dem. Rep. Congo": "Congo, Democratic Republic of the",
  "Eq. Guinea": "Equatorial Guinea",
  "Central African Rep.": "Central African Republic",
  "S. Sudan": "South Sudan",
  Brunei: "Brunei Darussalam",
  Somaliland: "Somalia",
  Vietnam: "Viet Nam",
  "W. Sahara": "Western Sahara",
  Iran: "Iran (Islamic Republic of)",
  Syria: "Syrian Arab Republic",
  Macedonia: "North Macedonia",
  "Bosnia and Herz.": "Bosnia and Herzegovina",
  "Czech Rep.": "Czechia",
  "Dominican Rep.": "Dominican Republic",
  "S. Korea": "Korea, Republic of",
  Laos: "Lao People's Democratic Republic",
  "Dem. Rep. Korea": "Korea, Democratic People's Republic of",
  "Falkland Is.": "Falkland Islands (Malvinas)",
  Russia: "Russian Federation",
  Moldova: "Moldova, Republic of",
  "United Kingdom": "United Kingdom of Great Britain and Northern Ireland",
  Palestine: "Palestine, State of",
};

export default _;
