const eu = [
  { country: "AT", alreadyVoted: true },
  { country: "BE", alreadyVoted: true },
  { country: "BG", alreadyVoted: true },
  { country: "HR", alreadyVoted: true },
  { country: "CY", alreadyVoted: true },
  { country: "CZ", alreadyVoted: true },
  { country: "DK", alreadyVoted: true },
  { country: "ES", alreadyVoted: true },
  { country: "FI", alreadyVoted: true },
  { country: "FR", alreadyVoted: true },
  { country: "DE", alreadyVoted: true },
  { country: "GR", alreadyVoted: true },
  { country: "HU", alreadyVoted: true },
  { country: "IE", alreadyVoted: true },
  { country: "IT", alreadyVoted: true },
  { country: "LV", alreadyVoted: true },
  { country: "LT", alreadyVoted: true },
  { country: "LU", alreadyVoted: true },
  { country: "MT", alreadyVoted: true },
  { country: "NL", alreadyVoted: true },
  { country: "PL", alreadyVoted: true },
  { country: "PT", alreadyVoted: true },
  { country: "RO", alreadyVoted: true },
  { country: "SK", alreadyVoted: true },
  { country: "SI", alreadyVoted: true },
  { country: "ES", alreadyVoted: true },
  { country: "SE", alreadyVoted: true },
].map((d) => ({
  ...d,
  alreadyVoted: true,
}));

export default eu;
